---
title: "viz_and_eda"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```


```{r data_import, cache=TRUE}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

```{r}

ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point()

weather_df %>%
  filter(name == "CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y = tmax)) + geom_point()

weather_save = ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point(aes(color=name))
```

add a geom
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point(aes(color = name), alpha = 0.4) + geom_smooth(se = FALSE)

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = 0.4) + geom_smooth(se = FALSE)

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)

```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point()

ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram() + facet_grid(. ~ name)

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + geom_boxplot()

ggplot(weather_df, aes(x = name, y = tmax)) + geom_violin()

ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)

ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

```{r}

ggplot(weather_df, aes(x = tmin, y = tmax, color = prcp)) + 
  geom_point(alpha = .5)

weather_df %>% 
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)

```

```{r}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```

